- resources/user.css
Close window control button now turns red when hovered over
Window control buttons no longer show a pointer cursor when hovered over - now uses default cursor, like other apps
> Enhanced window control buttons - hover effect and cursor change

- mods/core/css/theme.css
Font sizes remained the same as default for page previews. They are not affected by custom font sizes. This change takes the page variables and applies it. Tested and working 10/10
Full open pages: .notion-frame
Overlay, preview pages: .notion-overlay-container (and .notion-scroller.vertical WITHOUT .horizontal)
> Add font sizing to page previews

- DOCUMENTATION.md
Link error pointed out in the Discord
https://github.com/dragonwocky/notion-enhancer/blob/master/DOCUMENTATION.md#testing
->
https://github.com/dragonwocky/notion-enhancer/blob/master/CONTRIBUTING.md#testing
> docs: Fixed link to dev build instructions

- mods/tweaks/mod.js
- mods/tweaks/styles.css
Lets you scroll the toolbar on databases horizontally if part of the toolbar is hidden (scroll horizontally by holding **shift** while scrolling)
> New tweak: Scroll Database Toolbars

- mods/property-layout/mod.js
- mods/property-layout/styles.css
Modified the **property-layout** extension to look more like notion's toggles.
Before:
After:
> Property Layout Modification

- mods/core/tabs.css
these changes prevent the tabs section from wrapping. if the total width of all tabs is greater than the available width, non-current tabs are automatically shrink to prevent wrapping and make available space for new tabs.
up to ~~16~~ 15 tabs can be added, and after ~~16~~ 15 tabs have been added, the new tab adding button is removed. after a tab is removed, the add tab button returns. **take a look at this gif to see how this system works:**
> add auto-shrink system for tabs

- mods/notion-icons/mod.js
The default icon sets are now loaded using CSS sprites.
> Update notion-icons to work with sprite sheets

- README.md
Anything earlier than v2.0.8 is unsupported by notion enhancer and will not work. As both of the current linux clients listed in the README.md ([notion-app installer](https://github.com/jaredallard/notion-app) and [notion-deb-builder](https://github.com/haydn-jones/notion-deb-builder))  have their default set lower to this, it would be extremely valuable to the public to know this information.
> Add note about supported linux client versions

- mods/notion-icons/mod.js
The mod now observes changes on the overlay container instead of adding click listeners to every page icon.
This should make the modal detection smoother, and also fixes a few places where it just didn't work previously.
> Notion-icons: better popup modal detection

- mods/indentation-lines/mod.js
- mods/tweaks/app.css
- mods/tweaks/mod.js
this enables the option to toggle which types of lists should have indentation lines.
solves #277.
> move indentation lines from tweaks to its own mod

- mods/core/css/theme.css
- mods/core/variables.css
- mods/font-chooser/mod.js
- new quote variable for themes:
- **`--theme_dark--font_quote`**
- **`--theme_light--font_quote`**
- changes on @TorchAtlas's font chooser:
- added a warning saying that the desired fonts must be installed on the device.
- **`make sure the fonts you type are installed on your device.`**
- added a new input to change the font of quotes.
- version number: **`0.1.1`** -> ~~**`0.1.2`**~~ **`0.2.1`**.
> add quote variable for themes and quote input for font chooser

- mods/word-counter/mod.js
- added a new toggle to hide 'page details' text.
- version number: **`0.1.0`** -> **`0.2.0`**.
> option: hide 'page details' text for word counter

- mods/panel-sites/app.css
- mods/panel-sites/mod.js
- mods/panel-sites/panel.js
- mods/side-panel/mod.js
embed sites into the side panel extension.
users should provide a `json` file containing an array of `site` objects.
a site object can have the following properties:
| property |  description | type |
| ---------- | ------------ | ---- |
| `name` | the name that will be displayed on the panel switcher | string |
| `url`      | the url of the site | string |
| `icon` (optional) | a url pointing to an image file (local images not supported) | string |
| `mobile` (optional) | set to `true` to use a mobile user agent (this loads the mobile version of some sites) | boolean |
**not all sites will work. the login process for some sites will be hit-or-miss. this is due to limitations of the `iframe` tag and cross-origin restrictions.**
this is an example of a valid `json` file which contains two …
> new extension: panel-sites

- mods/collapsible-headers/app.css
- mods/collapsible-headers/mod.js
adds toggles to collapse header sections. requested by #317.
**because the content is actually still there, navigating the page using arrow keys will still focus on the hidden content.**
you can also toggle headers using `Ctrl` + `Enter`.
if you try to move a header while it's collapsed, its content will automatically "uncollapse".
you can move the collapsed content together with the header if you also select the content by dragging over the bottom of the header (because the content is technically still there, just hidden).
there are three toggle positions to choose from:
| left | right | inline |
| --- | ------| ------ |
| ![image](https://user-images.githubusercontent.com/54142180/101247257-163b6c00-374b-11eb-8e39-c8354f7baa7c.png) | …
> new extension: collapsible headers

- mods/core/menu.css
**problem:** if the avatar is not a perfect square, it takes the shape of an ellipse rather than a square.
- the width and height values of all avatars are fixed to 1em
- avatars now take the shape of a perfect square
<table border="0">
<tr>
<td><i>before</i></td>
<td><i>after</i></td>
</tr>
<tr>
<td><img alt="before" src="https://i.imgur.com/Pcc4PdW.png"></td>
<td><img alt="after" src="https://i.imgur.com/QC3PaGX.png"></td>
</tr>
</table>
> fix the sizing of avatars in enhancer menu

- mods/core/css/theme.css
- mods/core/variables.css
- mods/font-chooser/mod.js
- new font variables for headings:
- **`--theme_dark--font_headings`**
- **`--theme_light--font_headings`**
- fix quote variable for theming:
- **`--theme--font_quote: var(--theme_dark--font_sans);`** -> **`--theme--font_quote: var(--theme_dark--font_quote);`**
- **`--theme--font_quote: var(--theme_light--font_sans);`** -> **`--theme--font_quote: var(--theme_light--font_quote);`**
- changes on @TorchAtlas's font chooser:
- added a new input to change the font of headings.
- version number: **`0.2.1`** -> ~~**`0.3.1`**~~ **`0.3.0`**.
- solution for issue https://github.com/notion-enhancer/notion-enhancer/issues/318
> add font variables for headings, headings input for font chooser and fix quote variable

- mods/tweaks/app.css
- mods/tweaks/mod.js
- added a new toggle to hide empty sidebar arrow.
- version number: **`0.1.0`** -> **`0.2.0`**.
**note:** to understand the empty pages, you need to activate the toggle (to scan subpages) at least once and this is reset every time the notion is reopened. i haven't found a better way to save this yet, but this one works too.
> tweak: hide empty sidebar arrow

- mods/simpler-databases/app.css
- mods/simpler-databases/mod.js
adds a menu to inline databases to toggle ui elements.
this works on a per database basis, based on block id.
each view has its respective options, though a couple like the `+ item` and header bar toggles will persist between different views.
linked databases have two extra options: the replace title input and link arrow toggle
> new extension: simpler databases

- mods/pinky-boom-light/mod.js
**problem:** the title of all other modules in the enhancer is in lowercase. we must keep this culture consistent.
<table border="0">
<tr>
<td><i>before</i></td>
<td><i>after</i></td>
</tr>
<tr>
<td><img alt="before" src="https://i.imgur.com/HX3nFtH.png"></td>
<td><img alt="after" src="https://i.imgur.com/9F5GEuM.png"></td>
</tr>
</table>
> pinky boom theme: make the title lowercase

- README.md
as of [v2.0.11-6](https://github.com/davidbailey00/notion-linux/releases/tag/v2.0.11-6), `notion-linux` now provides pre-built enhanced packages in its repository :)
> Update links + install info for notion-linux

- pkg/helpers.js
This should allow the enhancer to work with the standard macOS Notion install location (`/Applications/Notion.app`) and the local user install location (`~/Applications/Notion.app`). I have tested this on my current machine and everything appears to be working!
> Add support for user-only Notion installs on macOS

- pkg/apply.mjs
**Which bug report or feature request do these changes address?**
This may seem a little nitpicking so let me explain the motivation.
I also made some [customization](https://github.com/kidonng/cherry/tree/master/scripts#block-notion-analytics) [scripts](https://github.com/kidonng/cherry/tree/master/scripts#notion-localization) for Notion, but they are nothing big like notion-enhancer so I just recommend installing via `curl script >> preload.js`. The problem is the script is bundled in to IIFEs `(() => {})()` without [a leading semicolon](https://stackoverflow.com/questions/1873983/what-does-the-leading-semicolon-in-javascript-libraries-do), so they won't work if appended directly after notion-enhacer.
To be honest this is more of an issue of myself rather than notion-enhancer, I can …
> Add trailing semicolon when appending to preload script
