notion-enhancer/desktop

pkg/apply.js
pkg/remove.js

Fixed typo in the path to binary (linux)

---

mods/font-chooser/mod.js

Added 4 new inputs for choosing fonts
Sans Serif and UI - Modifies sans serif font CSS variable, which is also used for UI
Serif - Modifies serif font CSS variable
Monospace - Modifies monospace font CSS variable
Code - Modifies code font CSS variable

NEW MOD: Font Chooser

---

README.md
mods/hide-help/mod.js
mods/hide-help/styles.css

Simple module to hide the built in help button for those that don't need it.

Add module to hide help button

---

mods/font-chooser/mod.js

Fixed a small bug where it stops iterating through the font options if it encounters a blank option.

Font chooser bug fix

---

mods/material-ocean/mod.js
mods/material-ocean/styles.css

adds material ocean to the list of mods in the enhancer

mods: add material ocean theme

---

mods/dracula-theme/dracula.css
mods/dracula-theme/mod.js

A theme created based on the official Dracula Theme palette found https://draculatheme.com/contribute/. I do not own Dracula, but thought it would be nice to share this with others.

Dracula Theme

---

mods/core/css/theme.css
mods/core/css/variables.css

See: https://github.com/dragonwocky/notion-enhancer/issues/155

Tweaking readability in text-blocks by adding new variables

---

mods/cherrycola/mod.js
mods/cherrycola/styles.css

Let me know if anything looks amiss! I've attached some theme testing screenshots below 👇
edit: I noticed "Brown" text shows up as the normal font color but haven't been able to resolve that and found it to happen in other themes as well, not sure if that's happening on your end, it's defined on [line 53](https://github.com/dragonwocky/notion-enhancer/pull/161/files#diff-0c092592be75504fb6636bfba7c36c0330d6ebb198368d04d4b575b6673a263dR53) as the brown used elsewhere.

theme: cherry cola

---

mods/cherrycola/mod.js
mods/cherrycola/styles.css

Some updates to the colors per comments on #161

theme: Cherry cola updates

---

mods/tweaks/mod.js
mods/tweaks/styles.css

Line now changes color according to block color.
Added line types:
- **Solid**
- **Dashed**
- **Dotted**
- **Soft**

Modified tweak: Indentation lines

---

mods/code-line-numbers/mod.js
mods/code-line-numbers/styles.css

Adds line numbering to code blocks, as suggested by #221.

Extension: Code Line Numbers

---

mods/code-line-numbers/mod.js

- Changed how line numbering are calculated so it accounts for line-wrapping (Fixes #272)
- Line numbers now update using a `ResizeObserver` to observe when the code blocks change sizes (adding a new line or removing a new line)
The number of lines wrapped is calculated by `lineWidth / blockWidth`, but it's not exact so line wrapping may not work perfectly. Any suggestions on a better way of doing this?

Fix #272 and other improvements on the code line numbers mod

---

mods/code-line-numbers/mod.js

Fixes the problems listed in #275.

Code line numbers: fix plain text issue and more exact wrapping calculations

---

mods/notion-icons/mod.js

- Fix a visual issue that happens for some when zoom level is higher than 100%
- Fix a bug where the icon tab is sometimes missing on preview pages

Notion Icons: fix visual issues and modal detection

---

mods/core/enhancerMenu.js
mods/core/menu.css

As suggested by #261.
Before:
After

Modify the enhancer menu's toggle styles to follow notion's toggles

---

mods/core/createWindow.js
mods/core/tray.js

Fix White Window Bug #298, as is described in https://github.com/notion-enhancer/notion-enhancer/issues/298#issuecomment-737280313.

Fix White Window Bug #298

---

mods/admiraldus-truncated-table-titles/app.css
mods/admiraldus-truncated-table-titles/mod.js

- remove **`admiraldus`** tag (i just learned that developer names can be searched)
- change avatar source from local image to external link (so i can remotely change)
- make curly braces consistent (pretty clear)

remove tag, change avatar source, make curly braces consistent

---

mods/nord/app.css
mods/nord/mod.js
mods/nord/variables.css

Add nord theme

---

mods/core/css/theme.css
mods/core/variables.css

adds the variables mentioned in #242 and #280 and a bunch more.
added variables:
- general ui
`--theme--primary_text`
`--theme--primary_indicator_text`
`--theme--primary_indicator_hover`
`--theme--divider`
- database
`--theme--table-border_row`
`--theme--table-border_column`
`--theme--table-border_selected`
- code
`--theme--code_parameter`
`--theme--code_constant`
`--theme--code_regex`
`--theme--code_class-name`
`--theme--code_selector`
`--theme--code_id`
`--theme--code_class`
`--theme--code_pseudo-element`
`--theme--code_pseudo-class`
`--theme--code_attribute`
`--theme--code_value`
`--theme--code_unit`
`--theme--code_annotation`
`--theme--code_decorator`
`--theme--code_boolean`
there are more code variables I haven't added that's specific to certain languages like markdown

theming bugfixes and additional variables

---

mods/dracula/app.css
mods/dracula/mod.js
mods/dracula/variables.css

updated the theme's variables based on dracula's [official spec](https://spec.draculatheme.com/) and [vs-code theme](https://github.com/dracula/visual-studio-code/).
here are a few comparisons to show some of the things i changed:
| changes | old | new |
| --------- | --- | --- |
| code | ![old_code](https://user-images.githubusercontent.com/54142180/101765769-5ec0a400-3b14-11eb-92d6-64e3a5d00670.png) | ![new_code](https://user-images.githubusercontent.com/54142180/101765791-6a13cf80-3b14-11eb-9a85-01e1841380e6.png) |
| sidebar icons | ![old_sidebar_icons](https://user-images.githubusercontent.com/54142180/101765823-7435ce00-3b14-11eb-88a1-899b017f1016.png) | ![new_sidebar_icons](https://user-images.githubusercontent.com/54142180/101765836-77c95500-3b14-11eb-96ab-79c60a82dbe2.png) |
| …

update dracula theme variables to use more official colors

---

README.md

https://github.com/notion-enhancer/notion-enhancer/issues/467#issuecomment-850826498

Update README to reference notion-app-enhanced

---

mods/code-line-numbers/app.css
mods/code-line-numbers/mod.js
mods/collapsible-headers/mod.js
mods/outliner/mod.js
mods/outliner/panel.js
mods/scroll-to-top/app.css
mods/scroll-to-top/arrow.svg
mods/scroll-to-top/mod.js
mods/side-panel/app.css
mods/side-panel/mod.js
mods/simpler-databases/app.css
mods/simpler-databases/mod.js

Fixed mods:
`code-line-numbers` `collapsible-headers` `outliner` `scroll-to-top` `side-panel` `simpler-databases`
Couple extra changes:
- scroll-to-top arrow icon
- side-panel toggle key changed to `ctrl` `alt` `\`

fixes for various mods

---

mods/core/createWindow.js
mods/core/systemMenu.js

fix open duplicate notion windows when click dock notion icon on macos bigsur

---

mods/view-scale/app.css
mods/view-scale/mod.js

Hi there!
That is the latest version of view-scale extension.
Nice to discuss at discord, and I'll look forward to the moment of the merge.
The extension preview is as follows
Thanks for reading

extension: view-scale
